# Generated by Django 4.1.7 on 2023-03-28 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colonne',
            fields=[
                ('titre_colonne', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ordre', models.IntegerField()),
            ],
            options={
                'db_table': 'colonne',
            },
        ),
        migrations.CreateModel(
            name='Taches',
            fields=[
                ('id_tache', models.AutoField(primary_key=True, serialize=False)),
                ('titre_tache', models.CharField(max_length=50)),
                ('ordre', models.IntegerField()),
                ('titre_colonne', models.ForeignKey(db_column='titre_colonne', on_delete=django.db.models.deletion.DO_NOTHING, to='kanban.colonne')),
            ],
            options={
                'db_table': 'taches',
            },
        ),
    ]
