# Generated by Django 4.1.7 on 2023-04-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_alter_colonne_id_colonne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taches',
            name='id_tache',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
