# Generated by Django 4.1.7 on 2023-03-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_alter_colonne_ordre_alter_taches_ordre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonne',
            name='ordre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='taches',
            name='ordre',
            field=models.IntegerField(),
        ),
    ]
